version: '3.8'
services:
  redis:
    image: redis
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - 7312:8000
    depends_on:
      - redis